### PR TITLE
fix(remindme): add maximum

### LINKED ISSUE #2002: bug: Validate Date - remind
**Describe the bug**

remind allows for an arbitrary date outside the range specified by ISO_8601. This errors out on when sending to discord the embed with an invalid DateTime.

9999-12-31 - Acceptable
10000-01-01 - Not allowed While technically a valid date, ISO_8601 does not allow dates past year 9999

**To Reproduce**

Run command `s!remind 10000-01-01 Do you like this`
While this reminder will never be triggered, when requesting the reminder using `s!remind show {id}`
The datetime is invalid and discord refuses the request.

**Expected behavior**

Datetime should be validated against ISO_8601 where the year is no more than 4 digits in length

**Screenshots**

**Additional context**

```
DiscordAPIError: Invalid Form Body
embed.timestamp: Could not parse +010000-08-22T00:00:00.000Z. Should be ISO8601.
embeds[0].timestamp: Could not parse +010000-08-22T00:00:00.000Z. Should be ISO8601.
    at RequestHandler.execute (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async SkyraMessage.send (/usr/src/app/node_modules/@skyra/editable-commands/dist/index.js:1:1104)
    at async CoreEvent.run (/usr/src/app/node_modules/@sapphire/framework/dist/events/command-handler/CoreCommandAccepted.js:15:28)
    at async CoreEvent._run (/usr/src/app/node_modules/@sapphire/framework/dist/lib/structures/Event.js:78:13)
```

### PR DESCRIPTION
**Pull request by kyranet**
Fixes #2002

### CODE REVIEW

File: src/commands/Misc/remindme.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export class UserCommand extends SkyraCommand {
 	}
 
 	public async create(message: Message, args: SkyraCommand.Args) {
-		const duration = await args.pick('timespan', { minimum: minutes(1) });
+		const duration = await args.pick('timespan', { minimum: minutes(1), maximum: years(1) });
```
Comment (favna) [inline src/commands/Misc/remindme.ts]:
```suggestion
		const duration = await args.pick('timespan', { minimum: minutes(1), maximum: years(200) });
```

1 year is very short. Lets allow at least 200.

**Review by favna — CHANGES_REQUESTED** [review]

File: src/commands/Misc/remindme.ts (hunk 1 above)
Comment (kyranet) [reply src/commands/Misc/remindme.ts]: That's too long, let's make it 5.
```suggestion
		const duration = await args.pick('timespan', { minimum: minutes(1), maximum: years(5) });
```

Comment (favna) [reply src/commands/Misc/remindme.ts]: Why is 200 too long? 200 years from now is 2222, not 10_000.

**Review by favna — APPROVED** [review]
