### PR TITLE
fix(listeners): log manual bans

### LINKED ISSUE #2184: bug: events.ban-add and events.ban-remove not creating moderation logs
**Describe the bug**

The event for ban & unban when done by other bots/manual are not posting moderation log.
Bot has enough permission (ban, audit log) for this action.
The configuration setting for `channels.logs.moderation` is enabled.
The configuration setting for `events.ban-add` and `events.ban-remove` are also set to a channel where Skyra can send messages.

**To Reproduce**

1. Ban or Unban someone manually from Discord

**Expected behavior**

It should post the moderation log when I manually ban or unban someone.

**Screenshots**
Screenshot 2022-02-01 at 22-10-28 Skyra Settings

Screenshot 2022-02-01 at 22-11-17 Discord - A New Way to Chat with Friends Communities

Screenshot 2022-02-01 at 22-10-01 Skyra Settings

Screenshot 2022-02-01 at 22-11-59 Discord - A New Way to Chat with Friends Communities

**Additional context**

It was previously working last time around 09/21/2021
Screenshot 2022-02-01 at 22-13-42 Discord - A New Way to Chat with Friends Communities

Support message link: https://discord.com/channels/254360814063058944/382531782387695616/938087109091270697

### PR DESCRIPTION
**Pull request by lveneris**
Fixes #2184.

Note that for reasons I have yet to determine it will only log every once in a while as opposed to every time when done by the bot. This may be due to use of different handling systems, but from what I can see it should work in the same way.

### CODE REVIEW

**Comment by kyranet** [comment]
Oops, old code that we didn't catch due to the lack of strict types...

By the way, the type that's emitted is GuildBan: https://discord.js.org/#/docs/discord.js/stable/class/GuildBan

File: src/listeners/guilds/bans/guildBanAdd.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { Listener } from '@sapphire/framework';
 import type { Guild, User } from 'discord.js';
 
 export class UserListener extends Listener {
-	public async run(guild: Guild, user: User) {
+	public async run({ guild, user }: { guild: Guild; user: User }) {
```
Comment (favna) [inline src/listeners/guilds/bans/guildBanAdd.ts]: Adjust the type as per Kyra's comment above and then it's good

**Review by favna — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]

**Review by favna — APPROVED** [review]
