### PR TITLE
fix(music): resolved all errors and issues

### LINKED ISSUE #80: Fix(music): When entering playback in the middle of a song, initial time is not set to song's time but rather 00:00.
From Kyra:

> Fix bug where when entering the playback in the middle of a song, an initial time is not set to the song's time, but rather starts from 00:00 even if the song is at 2:30

### PR DESCRIPTION
**Pull request by kyranet**
Fixes https://github.com/skyra-project/skyra.pw/issues/80

### CODE REVIEW

File: src/events/lavalink/rawLavalinkDestroy.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+import { Event, EventStore } from 'klasa';
+
+export default class extends Event {
+
+	public constructor(store: EventStore, file: string[], directory: string) {
+		super(store, file, directory, {
+			emitter: store.client.lavalink!,
+			event: 'destroy'
+		});
+	}
```
Comment (favna) [inline src/events/lavalink/rawLavalinkDestroy.ts:12]: Use `@ApplyOptions` please

File: src/events/lavalink/rawLavalinkDestroy.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+	public run(payload: LavalinkEvent) {
+		const manager = this.client.guilds.get(payload.guildId)?.music || null;
+		return this.client.emit(Events.LavalinkDestroy, manager, payload);
```
Comment (favna) [inline src/events/lavalink/rawLavalinkDestroy.ts]: This causes no issues in case manager is null?

File: src/events/lavalink/rawLavalinkDestroy.ts [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+	public constructor(store: EventStore, file: string[], directory: string) {
+		super(store, file, directory, {
+			emitter: store.client.lavalink!,
+			event: 'destroy'
+		});
+	}
+
+	public run(payload: LavalinkDestroyEvent) {
+		const manager = this.client.guilds.get(payload.guildId)?.music || null;
```
Comment (favna) [inline src/events/lavalink/rawLavalinkDestroy.ts]: is the `|| null` required? Just using optional chaining it will be ` | undefined` which is already falsey. If not required then apply same to `rawLavalinkEvents`

File: src/events/lavalink/rawLavalinkEvent.ts [hunk 4]
```diff
@@ -34,14 +38,6 @@ export default class extends Event {
...
-		if (isPlayerUpdate(payload)) {
-			return this.client.emit(Events.LavalinkPlayerUpdate, manager, payload);
-		}
-
-		if (isDestroy(payload)) {
-			return this.client.emit(Events.LavalinkDestroy, manager, payload);
-		}
-
 		this.client.emit(Events.Wtf, `${this.kHeader} OP code not recognized: ${payload.op}`);
 		this.client.emit(Events.Error, `           Payload: ${JSON.stringify(payload)}`);
```
Comment (favna) [inline src/events/lavalink/rawLavalinkEvent.ts:43]:
```suggestion
		this.client.emit(Events.Error, `\t\tPayload: ${JSON.stringify(payload)}`);
```

If we're indenting it

File: src/events/lavalink/rawLavalinkPlayerUpdate.ts [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+import { Event, EventStore } from 'klasa';
+
+export default class extends Event {
+
+	public constructor(store: EventStore, file: string[], directory: string) {
+		super(store, file, directory, {
+			emitter: store.client.lavalink!,
+			event: 'playerUpdate'
+		});
+	}
```
Comment (favna) [inline src/events/lavalink/rawLavalinkPlayerUpdate.ts:12]: Use `@ApplyOptions` please

**Review by favna — CHANGES_REQUESTED** [review]

File: src/events/lavalink/rawLavalinkDestroy.ts (hunk 1 above)
Comment (kyranet) [reply src/events/lavalink/rawLavalinkDestroy.ts:12]: Not possible as it's accessing to the `store` variable.

File: src/events/lavalink/rawLavalinkEvent.ts (hunk 4 above)
Comment (kyranet) [reply src/events/lavalink/rawLavalinkEvent.ts:43]: Those spaces are there to make it aligned.

image

File: src/events/lavalink/rawLavalinkPlayerUpdate.ts (hunk 5 above)
Comment (kyranet) [reply src/events/lavalink/rawLavalinkPlayerUpdate.ts:12]: Not possible as it's accessing to the `store` variable.

**Review by favna — APPROVED** [review]

File: src/events/lavalink/rawLavalinkDestroy.ts (hunk 1 above)
Comment (MrJacz) [reply src/events/lavalink/rawLavalinkDestroy.ts:12]: I mean it is, `"lavalink"`

Comment (kyranet) [reply src/events/lavalink/rawLavalinkDestroy.ts:12]: Not possible as `client.lavalink` is nullable.

Comment (MrJacz) [reply src/events/lavalink/rawLavalinkDestroy.ts:12]: why tf is client.lavalink nullable
(God Lavalink.js sucks, lemme switch skyra to lavacord)
