### PR TITLE
fix: conf shows not-set now

### LINKED ISSUE #894: bug: The settings command shows `null` instead of `Not Set`
**Describe the bug**

The settings command shows `null` instead of `Not Set`.

**To Reproduce**
1. Write 'Skyra, conf show messages'

**Expected behavior**

All three keys should have shown "Not Set"

**Screenshots**
image

**Additional context**

None.

### PR DESCRIPTION
**Pull request by favna**
image

closes #894

### CODE REVIEW

File: src/lib/util/SettingsUtils.ts [hunk 1]
```diff
@@ -48,7 +48,10 @@ export function displayEntry(entry: SchemaEntry, value: unknown, guild: Guild) {
 }
 
 export function displayEntrySingle(entry: SchemaEntry, value: unknown, guild: Guild) {
-	return entry.serializer!.stringify(value, guild) || 'Not Set';
+	const entryString = entry.serializer!.stringify(value, guild);
+
+	if (entryString === 'null') return guild.language.tget('COMMAND_CONF_SETTING_NOT_SET');
+	return entryString;
```
Comment (kyranet) [inline src/lib/util/SettingsUtils.ts]:
```suggestion
	return value === null
		? guild.language.tget('COMMAND_CONF_SETTING_NOT_SET')
		: entry.serializer!.stringify(value, guild);
```

**Review by kyranet — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]
