### PR TITLE
fix: filter bots from logs

### LINKED ISSUE #829: FIX: Moderation logs should ignore bots

### LINKED ISSUE #830: FIX: Reaction logs should ignore bots

### PR DESCRIPTION
**Pull request by favna**
I think this should do it anyway. Not 100% sure on the reaction logs though.

Fixes #829 
Fixes #830

### CODE REVIEW

File: src/events/rawMessageReactionAdd.ts [hunk 1]
```diff
@@ -54,16 +54,19 @@ export default class extends Event {
...
-		if (data.channel.guild.settings.get(GuildSettings.Selfmod.Reactions.WhiteList).includes(emoji)) return;
+		if (data.guild.settings.get(GuildSettings.Selfmod.Reactions.WhiteList).includes(emoji)) return;
 
 		this.client.emit(Events.ReactionBlacklist, data, emoji);
-		if (!data.channel.guild.settings.get(GuildSettings.Channels.ReactionLogs)
-			|| (!data.channel.guild.settings.get(GuildSettings.Events.Twemoji) && data.emoji.id === null)) return;
+		if (
+			(!data.guild.settings.get(GuildSettings.Channels.ReactionLogs))
+			|| (!data.guild.settings.get(GuildSettings.Events.Twemoji) && data.emoji.id === null)
+			|| (data.guild.members.get(data.userID)!.user.bot)
```
Comment (favna) [inline src/events/rawMessageReactionAdd.ts]: Highlighting this line as the actually added line

Comment (kyranet) [inline src/events/rawMessageReactionAdd.ts]: How bold of you to assume it's available.

**Review by kyranet — DISMISSED** [review]

**Review by kyranet — APPROVED** [review]

File: src/lib/util/Cache/UserTags.ts [hunk 2]
```diff
@@ -83,4 +84,5 @@ export interface UserTag {
 	readonly avatar: string | null;
 	readonly username: string;
 	readonly discriminator: string;
+	readonly bot?: boolean;
```
Comment (kyranet) [inline src/lib/util/Cache/UserTags.ts]:
```suggestion
	readonly bot: boolean;
```

**Review by kyranet — CHANGES_REQUESTED** [review]

**Review by kyranet — DISMISSED** [review]

**Review by kyranet — APPROVED** [review]
